# whenever new push comes in we would like to run this job
name: Deploy Project
on: [workflow_dispatch] # instead of just triggering on push, we can make it an array and run on many events. Previously was [push, workflow_dispatch]
jobs:
  # Job names are not fixed. you can come up with your name
  test:
    # You will always need to get the code into the working machine
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3 # uses for actions
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci # ci that installs packages locked inside of package-lock
      - name: Run tests
        run: npm test
  deploy:
    needs: test # refer to the job 'test'. you can also make it an array [test,job2,...so on]
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3 # uses for actions
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."
