# whenever new push comes in we would like to run this job
name: Test my react app
on: push
jobs:
  test:
    # You will always need to get the code into the working machine
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3 # uses for actions
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci # ci that installs packages locked inside of package-lock
      - name: Run tests
        run: npm test
